import MainHeader from './components/header/mainHeader'
import './globals.css'

import { Bebas_Neue } from 'next/font/google'

const bebasNeue = Bebas_Neue({
  subsets: ['latin'],
  weight: ['400']
})

export const metadata = {
  title: 'Display Control Manufacturing',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={bebasNeue.className}>
        <main className='flex flex-col h-[1200px] w-[1600px] p-[30px] bg-[#9DA5EE] gap-[25px]'>
          <MainHeader />
          <div className='col w-full h-[925px] flex gap-[30px]'>
            {children}
          </div>
        </main>
      </body>
    </html>
  )
}
